- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    when: ansible_distribution == "Ubuntu"

- name: start apache (Ubuntu)
  tags: apache,apache2,ubuntu
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for CentOS servers
  tags: apache,https,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: change email address for apache admin
  tags: apache,apache2,httpd
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Ubuntu"
  register: apache2

- name: restart apache2 (Ubuntu)
  tags: apache,apache2,httpd
  service:
    name: apache2
    state: restarted
  when: apache2.changed

- name: copy default site web page
  tags: apache,apache2,httpd
  copy:
    src: default-site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
